### ISSUE TITLE
Winograd vs CUDNN benchmarks

### ISSUE THREAD

**Issue by bhack** [moskewcz/boda#16]
What perforamce we could achive without a Winograd implementation? See last benchmark results at https://www.nervanasys.com/winograd-3/

**Comment by aryamazaheri** [comment]
@bhack We implemented a Winograd convolution for Boda.
https://github.com/TUD-UCB-Boda/boda/pull/8

Are you also interested in the performance comparison of Winograd/Direct convolutions in different frameworks?
