### ISSUE TITLE
Boda manual

### ISSUE THREAD

**Issue by chaeseok** [moskewcz/boda#4]
Hi,
Do you have a boda manual or something?

**Comment by moskewcz** [comment]
in short: nope. i guess we'll leave this issue open then. ;)

if you recall the first sentence of #1, boda is a:
"single-developer, single-machine, limited-documentation, under-constant-development grad-student project"

the aforementioned limited documentation consists of:
* the github issues
* the NESI 'help' strings embedded in the boda, used to print per-mode help
* the code comments
* the README, which may also link to the occasional poster / presentation. currently it's pretty out of date.
* the code itself
